extends Node

signal SPAWN_TAIL
signal UPDATE_TAIL
signal ADD_XP
signal SHOW_ACCEPT_MENU

signal FX_WEAK_HIT
signal FX_PLAYER_ATTACK
signal FX_SWORD_ATTACK

signal PLAY_SOUND_EFFECT

signal DATA_LOAD_SLOT
signal DATA_SAVE_SLOT

signal ROOM_LOAD
signal ROOM_CLEAR
signal ROOM_LOAD_NPC
signal ROOM_UNLOAD_NPC
signal ROOM_SHOW_PAUSE_MENU
signal ROOM_SWITCH_FLIPPED
signal ROOM_CHANGE_PARTY

signal ENEMY_DESTROYED

signal PLATFORM_DESTROYED
signal PLAYER_MOVE_TO

signal OPEN_TREASURE
