extends Node

signal SPAWN_TAIL
signal UPDATE_TAIL
signal INIT_TAIL
signal REMOVE_TAIL
signal SYNC_TAIL
signal ADD_XP
signal ADD_HP
signal SHOW_ACCEPT_MENU

signal FX_WEAK_HIT
signal FX_PLAYER_ATTACK
signal FX_SWORD_ATTACK
signal FX_SWORD_SLASH
signal FX_HIT_GROUND_DUST
signal FX_THIEF_KNIFE
signal FX_FIRE_BALL
signal FX_ELF_ARROW

signal PLAY_SOUND_EFFECT

signal DATA_LOAD_SLOT
signal DATA_SAVE_SLOT

signal ROOM_LOAD
signal ROOM_CLEAR
signal ROOM_LOAD_NPC
signal ROOM_UNLOAD_NPC
signal ROOM_SHOW_PAUSE_MENU
signal ROOM_SWITCH_FLIPPED
signal ROOM_CHANGE_PARTY

signal GAME_NEW_GAME

signal ENEMY_DESTROYED
signal ENEMY_SHOOT

signal PLATFORM_DESTROYED
signal PLAYER_MOVE_TO
signal PLAYER_REFILL_POTION
signal PLAYER_JUMP_BLOCK

signal OPEN_TREASURE
