extends Node

const enemy_enemySmall = preload("res://scenes/enemies/enemySmall.tscn")
const enemy_enemyBullet = preload("res://scenes/enemies/enemyBullet.tscn")
const player_tail = preload("res://scenes/player/tails/tail.tscn")
const fx_weakHit = preload("res://scenes/fx/weakHit.tscn")
const fx_fireball = preload("res://scenes/fx/fireBall.tscn")
const fx_thiefKnife = preload("res://scenes/fx/thiefKnife.tscn")
const fx_swordAttack = preload("res://scenes/fx/swordAttack.tscn")
const fx_swordSlash = preload("res://scenes/fx/swordSlash.tscn")
const fx_hitGroundDust = preload("res://scenes/fx/hitGroundDust.tscn")
const room_door = preload("res://scenes/map/door.tscn")
const room_npc = preload("res://scenes/map/npc.tscn")
const room_pushableBlock = preload("res://scenes/platforms/pushableBlock.tscn")
const room_stairs = preload("res://scenes/platforms/jumpThoughStairs1.tscn")
const room_treasure = preload("res://scenes/map/treasure.tscn")
const room_saveSpot = preload("res://scenes/platforms/saveSpot.tscn")
const room_switch_wood = preload("res://scenes/map/switch.tscn")

func getScene(type:Enums.spawnType):
	match type:
		Enums.spawnType.DOOR: return room_door.instantiate()
		Enums.spawnType.ENEMY_SMALL: return enemy_enemySmall.instantiate()
		Enums.spawnType.ENEMY_BULLET: return 
		Enums.spawnType.FX_WEAK_HIT: return fx_weakHit.instantiate()
		Enums.spawnType.FX_FIRE_BALL: return fx_fireball.instantiate()
		Enums.spawnType.FX_THIEF_KNIFE: return fx_thiefKnife.instantiate()
		Enums.spawnType.FX_SWORD_ATTACK: return fx_swordAttack.instantiate()
		Enums.spawnType.FX_SWORD_SLASH: return fx_swordSlash.instantiate()
		Enums.spawnType.FX_GROUND_HIT_DUST: return fx_hitGroundDust.instantiate()
		Enums.spawnType.PUSHABLE_BLOCK: return room_pushableBlock.instantiate()
		Enums.spawnType.NPC: return room_npc.instantiate()
		Enums.spawnType.SAVE_SPOT: return room_saveSpot.instantiate()
		Enums.spawnType.STAIRS: return room_stairs.instantiate()
		Enums.spawnType.SWITCH: return room_switch_wood.instantiate()
		Enums.spawnType.TREASURE: return room_treasure.instantiate()
		Enums.spawnType.TAIL: return player_tail.instantiate()
		_ : return enemy_enemySmall.instantiate()
